import Navbar from "@/components/Navbar";
import "../globals.css";
import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import { cn } from "@/lib/utils";
import { Container } from "@/components/ui/container";
import Sidebar from "@/components/Sidebar";
import NextAuthProvider from "@/components/SessionProvider";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";

const inter = Roboto_Mono({
  weight: ["300", "400", "700", "500"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  if (!session) {
    return redirect("/sign-in");
  }

  return (
    <html lang="en">
      <body className={cn(inter.className, "bg-slate-800 text-secondary")}>
        <NextAuthProvider>
          <Navbar />
          <main className="border-t border-slate-700">
            <Container>
              <div className="flex h-full max-h-screen scroll-smooth">
                <Sidebar />
                <div className="flex-1 pt-4">{children}</div>
              </div>
            </Container>
          </main>
        </NextAuthProvider>
      </body>
    </html>
  );
}
